services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=/app/app.db
      - GUNICORN_TIMEOUT=120
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
